### ISSUE TITLE
No module named raymock

### ISSUE THREAD

**Issue by svm-zhang** [biocore-ntnu/pyranges#5] opened 2019-04-19 03:41 UTC
Hello,

Thanks very much for bringing GRanges to python. Very much appreciated!

I tried to install pyranges through `pip install pyranges`. The installation issued no problems. However, when I tried to import pyranges, it complained about `No module named raymock`.

I did a quick fix by updating `import pyranges.ramock as ray` as `import ramock as ray` in the `pyranges.py`. But then it similarly complained other packages. I am wondering is there way I can just fix all automatically? Thanks for any help.

Simo

**Comment by endrebak** [comment] 2019-04-20 06:46
Thanks. Will fix this by a refactoring as soon as I get back on Monday. I
know what the problem is :)

**Comment by endrebak** [comment] 2019-04-20 07:00
What are the exact commands that made it fail? I want to see if I can
reproduce the error. Anyways, this is going to be fixed by a refactoring I
had planned anyways.

You could try pip install ray, import ray before you import pyranges and
see if it works. I did not want to have ray as a dependency for the
project, so I made a raymock library. But the current way I have of dealing
with the missing dependency is obviously not working too well.

Note to self: think of some ways of testing this :)

Endre

**Comment by svm-zhang** [comment] 2019-04-21 06:01
Thanks very much for getting back to me!

I followed your suggestions on install ray and import it before importing pyranges. However, `import ray` complains a `GLIBC` conflict I think. The error message is:

`/lib64/libc.so.6: version `GLIBC_2.14' not found`

I am using anaconda and it has a gcc 7.3.0. Not sure how I should get pass this one :)

Simo

**Comment by endrebak** [comment] 2019-04-21 06:14
So I really should not require ray then. I will fix this on Monday. I have
many ideas.

Btw you did not call your file pyranges or have a pyranges dir in the dir
you tried to run the file from? That could lead to your original error too.
But the code you found an error in is not robust and will be fixed Monday.

**Comment by svm-zhang** [comment] 2019-04-21 19:19
Thats correct. I tried to import pyranges from any generic location within which there was no pyranges dir. Looking forward to the fix :) Thanks!

**Comment by endrebak** [comment] 2019-04-22 09:39
Could you please try `pip install --no-cache-dir pyranges`? Should be fixed now :)

**Comment by endrebak** [comment] 2019-04-22 09:40
To prevent similar things from happening again I will set up tests with `tox` so that the library can be tested under different environments (for example with/without ray).

**Comment by svm-zhang** [comment] 2019-04-22 16:09
You are lighting fast on fixing this :)

The installation of v0.0.28 was successful. The error now is a similar one:`from pyrnages.tostring import tostring: No module named tostring`.

**Comment by endrebak** [comment] 2019-04-23 09:34
Is the spelling error yours (pyrnages)? :) Or is it copy and paste?

Anyways, what Python version are you using? I do not support legacy Python (version2), only Python 3.5 and up (3.4 was deprecated in March).

How did you install pyranges? I just did `pip install pyranges==0.0.28` and it works fine. It also works on TRAVIS.

What is your environment? macOS/Windows/Linux? 

What commands did you try? :)

Thanks for getting back to me so quickly.

**Comment by svm-zhang** [comment] 2019-04-23 17:33
Haha, thats my typo... 

I see the problem now. I am using python 2.7.15. Do you think there is a way I can get pass this? 

Simo

**Comment by endrebak** [comment] 2019-04-23 18:33
Download another version of python. Just google anaconda and you will find
a great installer :) I should add something to setup.py to notify 2.7
people that their python is not supported.

**Comment by svm-zhang** [comment] 2019-04-23 19:47
I have the anaconda python 2.7 env installed. Gonna have to deal with a different env if I install python 3 :). Anyway, I will try to install using a python3 env and report back. Thanks!

**Comment by endrebak** [comment] 2019-04-24 09:37
Yeah, Python2.7 is soon retiring: https://pythonclock.org/

And many of the libraries I depend on are not even updated for 2.7 anymore
so even if I wanted to make PyRanges work with 2.7 I would not be able to
:)

**Comment by svm-zhang** [comment] 2019-04-24 15:40
True.

I can confirm it works perfectly fine once I switched to python 3. Thanks for being such a great help.

Simo

**Closed** 2019-04-24 21:43 UTC

**Comment by endrebak** [comment] 2019-04-25 03:45
Thanks for reporting. I really needed to fix the ray stuff anyways :)
